apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{{name}}}-docker-config
data:
  .dockerconfigjson: {{{dockerConfigSecret}}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{{name}}}
  labels: 
    app: {{{name}}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{{name}}}
  template:
    metadata:
      labels:
        app: {{{name}}}
    spec:
      containers: 
      - name: main
        image: {{{imageRef}}}
        imagePullPolicy: Always
      imagePullSecrets:
      - name: {{{name}}}-docker-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{{name}}}
spec:
  selector:
    app: {{{name}}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
