name: CI Pipeline
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.16.3'
      - name: Package testing
        run: |
          git config --global user.email "ci@ci.com"
          git config --global user.name "CI pipeline"
          npm ci
          npm test